# Generated by Django 4.2.1 on 2023-05-30 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VoterID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('issue_date', models.CharField(max_length=50)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_citizen_data.citizen')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_citizen_data.citizen')),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('issue_date', models.CharField(max_length=50)),
                ('expiry_date', models.CharField(max_length=50)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_citizen_data.citizen')),
            ],
        ),
        migrations.CreateModel(
            name='PAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_citizen_data.citizen')),
            ],
        ),
        migrations.CreateModel(
            name='Malpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_citizen_data.citizen')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('issue_date', models.CharField(max_length=50)),
                ('expiry_date', models.CharField(max_length=50)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_citizen_data.citizen')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeesProvidentFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_citizen_data.citizen')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=50)),
                ('board', models.CharField(max_length=50)),
                ('institution', models.CharField(max_length=50)),
                ('from_year', models.CharField(max_length=50)),
                ('to_year', models.CharField(max_length=50)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_citizen_data.citizen')),
            ],
        ),
        migrations.CreateModel(
            name='DrivingLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('renewal_date', models.CharField(max_length=50)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_citizen_data.citizen')),
            ],
        ),
        migrations.CreateModel(
            name='Citizenship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('issue_date', models.CharField(max_length=50)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_citizen_data.citizen')),
            ],
        ),
        migrations.CreateModel(
            name='BlueBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('renewal_date', models.CharField(max_length=50)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_citizen_data.citizen')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=50)),
                ('branch_name', models.CharField(max_length=50)),
                ('account_type', models.CharField(max_length=50)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_citizen_data.citizen')),
            ],
        ),
    ]
